# Generated by Django 3.2 on 2023-09-15 07:53

from django.db import migrations, models
import main_config.tools


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230915_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=main_config.tools.UploadToPathAndRename('products'), verbose_name='product image'),
        ),
    ]
