# Generated by Django 3.2 on 2023-09-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMonetaryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='option')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product monetary option',
                'verbose_name_plural': 'product monetary options',
            },
        ),
    ]
