# Generated by Django 3.2 on 2023-09-22 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230922_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact_us',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
